kind: Service
apiVersion: v1

metadata:
  name: test-service
  namespace: nginx
  labels:
    app: test-app
spec:
  selector:
    app: test-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
